zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")

zn "USER"
; run installer to create namespace
do $SYSTEM.OBJ.Load("/tmp/iris/Installer.cls", "ck")
set sc = ##class(App.Installer).setup() 

zn "IRISAPP"
zw $SYSTEM.OBJ.ImportDir("/tmp/iris/src", "*.cls", "cubk", .tErrors, 1)

zpm "install csvgen"

do ##class(community.csvgen).Generate("/tmp/iris/misc/titanic.csv",",","Titanic.Table.Passenger")


h