Class Titanic.Table.Passenger Extends (%Persistent, Titanic.Definition.Passenger)
{

Storage Default
{
<Data name="PassengerDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Class</Value>
</Value>
<Value name="3">
<Value>Survived</Value>
</Value>
<Value name="4">
<Value>Name</Value>
</Value>
<Value name="5">
<Value>Sex</Value>
</Value>
<Value name="6">
<Value>Age</Value>
</Value>
<Value name="7">
<Value>Sibsp</Value>
</Value>
<Value name="8">
<Value>Parch</Value>
</Value>
<Value name="9">
<Value>Ticket</Value>
</Value>
<Value name="10">
<Value>Fare</Value>
</Value>
<Value name="11">
<Value>Cabin</Value>
</Value>
<Value name="12">
<Value>Embarked</Value>
</Value>
<Value name="13">
<Value>Boat</Value>
</Value>
<Value name="14">
<Value>Body</Value>
</Value>
<Value name="15">
<Value>Destination</Value>
</Value>
<Value name="16">
<Value>Id</Value>
</Value>
</Data>
<DataLocation>^Titanic.Table.PassengerD</DataLocation>
<DefaultData>PassengerDefaultData</DefaultData>
<IdLocation>^Titanic.Table.PassengerD</IdLocation>
<IndexLocation>^Titanic.Table.PassengerI</IndexLocation>
<StreamLocation>^Titanic.Table.PassengerS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
